define({
    root : {
        "headerText" : "BRIKOLEUR",
        "footerText" : "by Creative Workers’ Collective “Alexander Bogdanov”",
        "OutOfPlay" : "Out of Play",
        "InPlay" : "In Play",
        "CreateCharacter" : "Create",
        "CharacterName" : "Character name",
        "Juju" : "Juju",
        "Body" : "Body",
        "Mind" : "Mind",
        "Description" : "Description",
        "Gear" : "Gear",
        "Numbers" : "Numbers",
        "Traits" : "Traits",
        "Knacks" : "Knacks",
        "KnacksAndTraining" : "Knacks and Training",
        "Powers" : "Powers",
        "Stunts" : "Stunts",
        "Ohun" : "Ohun",
        "Stamina" : "Stamina",
        "Armour" : "Armour",
        "Weapon" : "Weapon",
        "Level" : "Level ",
        "Type": "Type",
        "Lvl" : "Lvl",
        "Save" : "Save",
        "Delete" : "Delete",
        "Revert" : "Revert",
        "Roster" : "Roster",
        "NameInUse" : "The name is already in use.",
        "ItemDescription" : "Description",
        "ActivePowerSlots" : "Active Powers",
        "OhunSlots" : "Ohun",
        "SelectOrType" : "Invent or select",
        "TrainingPresent" : "You already have this training.",
        "SpecialisationPresent" : "You already have this specialisation.",
        "StuntPresent" : "You already have this stunt.",
        "PowerPresent" : "You already have this power.",
        "AdHocOhunDescription" : "You may ${verb} up to ${cap} ${name} (level ${min}-${max}).",
        "Gender" : "Gender",
        "Handle" : "Handle",
        "Ekip" : "Ekip",
        "Background" : "Background"
    }
});