define({
    root : {
        "headerText" : "BRIKOLEUR",
        "footerText" : "by Creative Workers’ Collective “Alexander Bogdanov”",
        "OutOfPlay" : "Out of Play",
        "InPlay" : "In Play",
        "CreateCharacter" : "Create",
        "CharacterName" : "Character name",
        "Juju" : "Juju",
        "Body" : "Body",
        "Mind" : "Mind",
        "Description" : "Description",
        "Gear" : "Gear",
        "Numbers" : "Numbers",
        "Traits" : "Traits",
        "Knacks" : "Knacks",
        "KnacksAndTraining" : "Knacks and Training",
        "Powers" : "Powers",
        "Stunts" : "Stunts",
        "Ohun" : "Ohun",
        "Stamina" : "Stamina",
        "Armour" : "Armour",
        "Level" : "Level ",
        "ActivePowerSlots" : "Active Power Slots",
        "OhunSlots" : "Ohun Slots",
        "SelectOrType" : "Invent or select",
        "TrainingPresent" : "You already have this training.",
        "SpecialisationPresent" : "You already have this specialisation.",
        "StuntPresent" : "You already have this stunt.",
        "PowerPresent" : "You already have this power.",
        "AdHocOhunDescription" : "You may ${verb} up to ${cap} ${name} (level ${min}-${max})."
    }
});